name             'rbmonitor'
maintainer       'Eneo Tecnología S.L.'
maintainer_email 'git@redborder.com'
license          'AGPL-3.0'
description      'Installs/Configures rb-monitor'
version          '0.6.0'
